### ISSUE TITLE
Add more data to the Rewind 

### ISSUE THREAD

**Issue by VozDeOuro** [RaunoT/plex-rewind#134]
### Description

Hey there,

I've been using [Wrapperr](https://github.com/aunefyren/wrapperr) and just found your Rewind project. I really like it, but I think it could be even better with a couple of additions:

    Text Prompts: Wrapperr has some great text prompts that make it split more info. Adding something similar to Rewind would be awesome like oldest movie, longest pause and % of conclusion of the movie/serie .
    Fun Prompts: There are also some fun prompts in Wrapperr that add a bit of personality. Including these would make Rewind more engaging.

Also, it would be super cool if the top movie and series had their soundtrack play on the website. It would make the experience more immersive.

Thanks for considering these ideas. Looking forward to seeing Rewind get even better!

### Desired behavior

Described above.

**Comment by RaunoT** [comment]
Thanks for this @VozDeOuro, I definitely agree that these would be great additions. I'm aware that the Rewind functionality is rather bare-bones currently and it's definitely a high priority for me to improve it.

That said, since adding more data to Rewind will be a continual process anyway and this ticket is kind of general, I will close it for now. But be sure to check in for updates regarding this hopefully soon 🚀

**Comment by VozDeOuro** [comment]
Sorry for bothering you again, just for curiosity, do you think that will be implemented until the end of October ?
I really want to use Plex-rewind this year :)

**Comment by RaunoT** [comment]
Since november kicks off "wrapped season" for most platforms, I will definitely try to get some progress in updating the available data in Rewind by then. No promises, but definitely a goal :)
