### ISSUE TITLE
Make movie top 5 based on number of plays, fall back to play time

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#186]
### Description

![image](https://github.com/user-attachments/assets/cae9cad9-9eef-41a2-95a5-d8b0ed6ba688)

In this example Oppenheimer was played 6 times vs The creator and Napoleon 8 times this year. 
Because Oppenheimer is a longer movie is it n1 but it should not be.

![image](https://github.com/user-attachments/assets/ae0ffc38-294a-431a-b185-ce3d10525b6e)

In this example poor things is the only movie that was played twice but it is 3rd in playtime.

### Desired behavior

For movies only, order by default based on number of plays, if a tie you can fall back to play time.

Bonus suggestion: add a piece of text somewhere on the page with a quick description "top movies based on watch time" to make it clear to users what the ranking is based on.

**Comment by RaunoT** [comment]
The reason I opted for going with time instead of plays, is that a play doesn't neccessarily mean a full play.
I'm open to adding a toggle for sorting style in the settings, but it would be global, not by library.

**Comment by SnippetSpace** [comment]
Fair enough. Would it be possible to add least add a descriptive label to the pages that shows what the top 5 is based upon so users don’t have to guess?

**Comment by RaunoT** [comment]
A sort by filter is now available. However, when the play counts are even, it does not fall back to duration. That's not the way the Tautulli API returns the data and since Plex Rewind is fully dynamic, it's not feasible to make expensive calculations and additional fetches on our end to achieve this behaviour on every render. 

For now, the sort by filter now works in the same way as the same filter in Tautulli.

<img width="584" alt="image" src="https://github.com/user-attachments/assets/4828a9c4-4c9f-4dc6-9c6e-6182fffd4aa2">
