### ISSUE TITLE
New image proxy broken for posters of requested movies

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#187]
### Plex Rewind Version

2.4.0-develop.6

### Description

Some posters not loading with new image proxy. 
They seem to all have the "request" label

### Steps to reproduce

1. do not expose tautulli publicly and use new rewind proxy
2. have requested movie in the top 5 in either dashboard or rewind

### Screenshots

Plex rewind dashboard:
![image](https://github.com/user-attachments/assets/f1d2baa2-5e0e-40f7-b79f-2ea89d97520a)

Plex rewind - rewind:
![image](https://github.com/user-attachments/assets/169b84ab-38c6-4df4-bbf8-e1a2f1042bf1)

Image does show in Tautulli:
![image](https://github.com/user-attachments/assets/68c62cd1-aaf6-4066-93e5-4ac24a99df6c)

### Logs

```shell
Edge error:

Failed to load resource: the server responded with a status of 400 ()
https://rewind.URL.com/_next/image?url=%2Fapi%2Fimage%3Furl%3Dhttp%253A%252F%252F192.168.1.77%253A18181%252Fpms_image_proxy%253Fimg%253D%252Flibrary%252Fmetadata%252F287990%252Fthumb%252F1697158626%2526width%253D300&w=256&q=75
```

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser and version

Edge v126

**Comment by RaunoT** [comment]
This error happens, because Tautulli doesn't return the image.

If you think about it, it kind of makes sense, that images are missing for items showing the Request button. The visibility of the request button means that the show/movie is no longer available on Plex. After being deleted, Tautulli (or Plex for that matter) might have deleted the image alongside it. 

I'm not quite sure on how long Tautulli retains images for deleted items, but it does seem to do so for at least some time. I guess as a workaround, what we could do in these cases, is return the poster from TMDB instead.

<img width="567" alt="image" src="https://github.com/user-attachments/assets/daa13253-de75-4cae-b09c-2ca7eb14e579">
<img width="616" alt="image" src="https://github.com/user-attachments/assets/2d857ea3-1f5f-4a36-81ba-7bb8e05a1960">
<img width="574" alt="image" src="https://github.com/user-attachments/assets/454069ba-a582-47b5-9b89-f33608c310eb">
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/0ee77f21-2e12-41fa-aef2-8c21fdb84b67">

**Comment by SnippetSpace** [comment]
@RaunoT not sure I understand the mechanism. All these items exist in Plex, they have not been deleted.

They also show as available in overseerr.

**Comment by RaunoT** [comment]
That's rather interesting. The request button should only be shown for deleted items. Will look into it under this same ticket.

**Comment by SnippetSpace** [comment]
Any logs I can send your way or something to debug?
