### ISSUE TITLE
Add Public share url 

### ISSUE THREAD

**Issue by Cousclou** [RaunoT/plex-rewind#209]
### Description

Allow sharing of a public link to display the user's statistics when he wishes to share them with people outside the Plex service

### Desired behavior

Allow sharing of a public link to display the user's statistics when he wishes to share them with people outside the Plex service

**Comment by RaunoT** [comment]
This is already available since [3.0.0-develop.4](https://github.com/RaunoT/plex-rewind/releases/tag/v3.0.0-develop.4) under `Settings -> General -> Privacy -> Allow outside` access and will be part of the next stable release. You will need to use a reverse proxy to expose the URL.

<img width="306" alt="image" src="https://github.com/user-attachments/assets/48f3d7f9-e950-44e0-b99d-dc28bd625647">
