### ISSUE TITLE
REQUEST: Configuration guide

### ISSUE THREAD

**Issue by BeansIsFat** [RaunoT/plex-rewind#21]
Could you put together a brief configuration guide and, ideally, a sample `docker-compose.yml`? 

Any chance you'll be publishing and maintaining a docker image for this?

**Comment by RaunoT** [comment]
@BeansIsFat There are still quite a few assumptions made on the code side which is why I've put it off so far. For more info take a look at #7 and #22. I'm finishing up #20 in the coming days and then will take a look at putting together a brief setup/config guide and tackling the aforementioned issues.

**Comment by RaunoT** [comment]
@BeansIsFat I've added a sample `docker-compose.yml` and [getting started instructions](https://github.com/RaunoT/plex-rewind?tab=readme-ov-file#getting-started) to get you started. Let me know how it works out 🙏
