### ISSUE TITLE
Add ability to see managed user's Rewinds

### ISSUE THREAD

**Issue by Jobinrandhawa** [RaunoT/plex-rewind#37]
I have a login for my admin account on Plex that no one uses but I use a managed user and because I use the login of the admin account to access my managed user I cannot see the rewind for the managed user.

**Comment by tarunkumar519** [comment]
This is the most important feature for alot of users. Hope this can be implemented soon

**Comment by RaunoT** [comment]
Open to suggestions on how to handle this flow.
Would we still require login then? Do we expect managed users to be able to know the plex login details? 

One way I see it, is that when a Plex Home admin login is used, after login there will be separate Rewind buttons for every managed user.

**Comment by tarunkumar519** [comment]
Plex home admin login details are used. After login there will be separate account buttons of managed users to select. But a managed user must have access to their own account and not anybody else.

so a separate PIN based authentication method for managed users like Plex already does? Could be any method.

**Comment by RaunoT** [comment]
@tarunkumar519 If the user logs in with admin login details and is showed multiple choices to pick a user whos Rewind to see, there is no way to ensure that _"managed user must have access to their own account and not anybody else"_. A user using admin login details, for all intensive purposes, is the admin.

I think that if you share your admin login details with a managed users, having them have the ability to see your Rewind isn't a real added security risk.

If we bypass the whole authentication, we would need to show Rewind buttons for every user on the server, since there is no other way to know who is viewing the site.
